/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.softwerke.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyArticle service. Represents a row in the &quot;journal_MyArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.softwerke.srv.model.impl.MyArticleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.softwerke.srv.model.impl.MyArticleImpl}.
 * </p>
 *
 * @author Sasha
 * @see MyArticle
 * @see com.softwerke.srv.model.impl.MyArticleImpl
 * @see com.softwerke.srv.model.impl.MyArticleModelImpl
 * @generated
 */
public interface MyArticleModel extends BaseModel<MyArticle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my article model instance should use the {@link MyArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this my article.
	 *
	 * @return the primary key of this my article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my article.
	 *
	 * @param primaryKey the primary key of this my article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this my article.
	 *
	 * @return the uuid of this my article
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this my article.
	 *
	 * @param uuid the uuid of this my article
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the my article ID of this my article.
	 *
	 * @return the my article ID of this my article
	 */
	public long getMyArticleId();

	/**
	 * Sets the my article ID of this my article.
	 *
	 * @param myArticleId the my article ID of this my article
	 */
	public void setMyArticleId(long myArticleId);

	/**
	 * Returns the my article name of this my article.
	 *
	 * @return the my article name of this my article
	 */
	@AutoEscape
	public String getMyArticleName();

	/**
	 * Sets the my article name of this my article.
	 *
	 * @param myArticleName the my article name of this my article
	 */
	public void setMyArticleName(String myArticleName);

	/**
	 * Returns the my article content of this my article.
	 *
	 * @return the my article content of this my article
	 */
	@AutoEscape
	public String getMyArticleContent();

	/**
	 * Sets the my article content of this my article.
	 *
	 * @param myArticleContent the my article content of this my article
	 */
	public void setMyArticleContent(String myArticleContent);

	/**
	 * Returns the my article refuse comment of this my article.
	 *
	 * @return the my article refuse comment of this my article
	 */
	@AutoEscape
	public String getMyArticleRefuseComment();

	/**
	 * Sets the my article refuse comment of this my article.
	 *
	 * @param myArticleRefuseComment the my article refuse comment of this my article
	 */
	public void setMyArticleRefuseComment(String myArticleRefuseComment);

	/**
	 * Returns the my article status of this my article.
	 *
	 * @return the my article status of this my article
	 */
	public int getMyArticleStatus();

	/**
	 * Sets the my article status of this my article.
	 *
	 * @param myArticleStatus the my article status of this my article
	 */
	public void setMyArticleStatus(int myArticleStatus);

	/**
	 * Returns the is my article published of this my article.
	 *
	 * @return the is my article published of this my article
	 */
	public boolean getIsMyArticlePublished();

	/**
	 * Returns <code>true</code> if this my article is is my article published.
	 *
	 * @return <code>true</code> if this my article is is my article published; <code>false</code> otherwise
	 */
	public boolean isIsMyArticlePublished();

	/**
	 * Sets whether this my article is is my article published.
	 *
	 * @param isMyArticlePublished the is my article published of this my article
	 */
	public void setIsMyArticlePublished(boolean isMyArticlePublished);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.softwerke.srv.model.MyArticle myArticle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.softwerke.srv.model.MyArticle> toCacheModel();

	@Override
	public com.softwerke.srv.model.MyArticle toEscapedModel();

	@Override
	public com.softwerke.srv.model.MyArticle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}