/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.softwerke.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MyReview service. Represents a row in the &quot;journal_MyReview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.softwerke.srv.model.impl.MyReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.softwerke.srv.model.impl.MyReviewImpl}.
 * </p>
 *
 * @author Sasha
 * @see MyReview
 * @see com.softwerke.srv.model.impl.MyReviewImpl
 * @see com.softwerke.srv.model.impl.MyReviewModelImpl
 * @generated
 */
public interface MyReviewModel extends BaseModel<MyReview> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my review model instance should use the {@link MyReview} interface instead.
	 */

	/**
	 * Returns the primary key of this my review.
	 *
	 * @return the primary key of this my review
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my review.
	 *
	 * @param primaryKey the primary key of this my review
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this my review.
	 *
	 * @return the uuid of this my review
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this my review.
	 *
	 * @param uuid the uuid of this my review
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the my review ID of this my review.
	 *
	 * @return the my review ID of this my review
	 */
	public long getMyReviewId();

	/**
	 * Sets the my review ID of this my review.
	 *
	 * @param myReviewId the my review ID of this my review
	 */
	public void setMyReviewId(long myReviewId);

	/**
	 * Returns the my review date creation of this my review.
	 *
	 * @return the my review date creation of this my review
	 */
	public Date getMyReviewDateCreation();

	/**
	 * Sets the my review date creation of this my review.
	 *
	 * @param myReviewDateCreation the my review date creation of this my review
	 */
	public void setMyReviewDateCreation(Date myReviewDateCreation);

	/**
	 * Returns the my review date modification of this my review.
	 *
	 * @return the my review date modification of this my review
	 */
	public Date getMyReviewDateModification();

	/**
	 * Sets the my review date modification of this my review.
	 *
	 * @param myReviewDateModification the my review date modification of this my review
	 */
	public void setMyReviewDateModification(Date myReviewDateModification);

	/**
	 * Returns the my review article ID of this my review.
	 *
	 * @return the my review article ID of this my review
	 */
	public long getMyReviewArticleId();

	/**
	 * Sets the my review article ID of this my review.
	 *
	 * @param myReviewArticleId the my review article ID of this my review
	 */
	public void setMyReviewArticleId(long myReviewArticleId);

	/**
	 * Returns the my review name of this my review.
	 *
	 * @return the my review name of this my review
	 */
	@AutoEscape
	public String getMyReviewName();

	/**
	 * Sets the my review name of this my review.
	 *
	 * @param MyReviewName the my review name of this my review
	 */
	public void setMyReviewName(String MyReviewName);

	/**
	 * Returns the my review content of this my review.
	 *
	 * @return the my review content of this my review
	 */
	@AutoEscape
	public String getMyReviewContent();

	/**
	 * Sets the my review content of this my review.
	 *
	 * @param MyReviewContent the my review content of this my review
	 */
	public void setMyReviewContent(String MyReviewContent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.softwerke.srv.model.MyReview myReview);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.softwerke.srv.model.MyReview> toCacheModel();

	@Override
	public com.softwerke.srv.model.MyReview toEscapedModel();

	@Override
	public com.softwerke.srv.model.MyReview toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}