/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.softwerke.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Review service. Represents a row in the &quot;new_perfect_journal_Review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.softwerke.srv.model.impl.ReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.softwerke.srv.model.impl.ReviewImpl}.
 * </p>
 *
 * @author Sasha
 * @see Review
 * @see com.softwerke.srv.model.impl.ReviewImpl
 * @see com.softwerke.srv.model.impl.ReviewModelImpl
 * @generated
 */
public interface ReviewModel extends BaseModel<Review> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a review model instance should use the {@link Review} interface instead.
	 */

	/**
	 * Returns the primary key of this review.
	 *
	 * @return the primary key of this review
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this review.
	 *
	 * @param primaryKey the primary key of this review
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this review.
	 *
	 * @return the uuid of this review
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this review.
	 *
	 * @param uuid the uuid of this review
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the review ID of this review.
	 *
	 * @return the review ID of this review
	 */
	public long getReviewId();

	/**
	 * Sets the review ID of this review.
	 *
	 * @param reviewId the review ID of this review
	 */
	public void setReviewId(long reviewId);

	/**
	 * Returns the group ID of this review.
	 *
	 * @return the group ID of this review
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this review.
	 *
	 * @param groupId the group ID of this review
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the review name of this review.
	 *
	 * @return the review name of this review
	 */
	@AutoEscape
	public String getReviewName();

	/**
	 * Sets the review name of this review.
	 *
	 * @param reviewName the review name of this review
	 */
	public void setReviewName(String reviewName);

	/**
	 * Returns the review content of this review.
	 *
	 * @return the review content of this review
	 */
	@AutoEscape
	public String getReviewContent();

	/**
	 * Sets the review content of this review.
	 *
	 * @param reviewContent the review content of this review
	 */
	public void setReviewContent(String reviewContent);

	/**
	 * Returns the article ID of this review.
	 *
	 * @return the article ID of this review
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this review.
	 *
	 * @param articleId the article ID of this review
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the user ID of this review.
	 *
	 * @return the user ID of this review
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this review.
	 *
	 * @param userId the user ID of this review
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this review.
	 *
	 * @return the user uuid of this review
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this review.
	 *
	 * @param userUuid the user uuid of this review
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.softwerke.srv.model.Review review);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.softwerke.srv.model.Review> toCacheModel();

	@Override
	public com.softwerke.srv.model.Review toEscapedModel();

	@Override
	public com.softwerke.srv.model.Review toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}